

#=================================================================================
# 是否生成ddl语句
spring.jpa.generate-ddl: false
# 是否打印sql语句
spring.jpa.show-sql: true
# 自动生成ddl，由于指定了具体的ddl，此处设置为none
spring.jpa.hibernate.ddl-auto: none
# 使用H2数据库
spring.datasource.platform: h2
# 指定生成数据库的schema文件位置
spring.datasource.schema: classpath:schema.sql
# 指定插入数据库语句的脚本位置
spring.datasource.data: classpath:data.sql
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/spring_boot_ci_demo?useSSL=false&autoReconnect=true&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&character_set_client=utf8mb4&character_set_connection=utf8mb4&character_set_database=utf8mb4&character_set_results=utf8mb4&character_set_server=utf8mb4&character_set_system=utf8&character_set_filesystem=binary&collation_connection=utf8mb4_unicode_ci&collation_database=utf8mb4_unicode_ci&collation_server=utf8mb4_unicode_ci
#    username: root
#    password: 123456
#=================================================================================

server:
  port: 8090



#=================================================================================

